version: 2
jobs:
  build:
    docker:
      - image: docker:18-git
    working_directory: ~/ci-build/
    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker login -username $DOCKER_USER --password-stdin $DOCKER_PASS

          docker build -t labsai/ci-build:b$CIRCLE_BUILD_NUM .
          docker push labsai/ci-build:b$CIRCLE_BUILD_NUM

          docker build -t labsai/ci-build:latest .
          docker push labsai/ci-build:latest
